import type { Article } from './types';

/** N日前のISO文字列 */
function daysAgo(n: number): string {
  return new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString();
}

/**
 * ネットワーク不通やAPI障害時のフォールバック用サンプル記事。
 * 本番（GitHub Actions上のビルド）では実APIの取得結果に置き換わる。
 * 公開日時は実行時刻からの相対で生成し、常に各期間に収まるようにする。
 */
export const sampleArticles: Article[] = [
  {
    id: 'qiita:sample-1',
    title: '個人開発で月10万円を達成するまでにやったこと全部',
    url: 'https://qiita.com/',
    author: 'sample_dev',
    authorUrl: 'https://qiita.com/',
    likes: 1842,
    source: 'qiita',
    tags: ['個人開発', 'ポエム', 'マネタイズ'],
    publishedAt: daysAgo(0),
    excerpt:
      '個人開発を3年続けて得た知見をまとめます。アイデアの選び方、最初のユーザー獲得、収益化の現実的なステップについて、失敗も含めて具体的に書きました。',
  },
  {
    id: 'zenn:sample-1',
    title: 'TypeScriptの型パズルを実務で使える形に落とし込む',
    url: 'https://zenn.dev/',
    author: 'sample_ts',
    authorUrl: 'https://zenn.dev/',
    likes: 1230,
    source: 'zenn',
    tags: ['TypeScript', 'フロントエンド'],
    publishedAt: daysAgo(0),
    excerpt: '',
  },
  {
    id: 'qiita:sample-2',
    title: 'LLMアプリ開発、RAGの精度を上げる10の実践テクニック',
    url: 'https://qiita.com/',
    author: 'ai_engineer',
    authorUrl: 'https://qiita.com/',
    likes: 980,
    source: 'qiita',
    tags: ['LLM', 'RAG', 'AI', 'Python'],
    publishedAt: daysAgo(1),
    excerpt:
      'チャンク分割、リランキング、ハイブリッド検索など、RAGの検索精度を改善するために現場で効果のあった手法を、計測結果とともに紹介します。',
  },
  {
    id: 'zenn:sample-2',
    title: 'Rustで作る自作データベース入門',
    url: 'https://zenn.dev/',
    author: 'rustacean',
    authorUrl: 'https://zenn.dev/',
    likes: 870,
    source: 'zenn',
    tags: ['Rust', 'データベース'],
    publishedAt: daysAgo(2),
    excerpt: '',
  },
  {
    id: 'qiita:sample-3',
    title: 'もう迷わないGitブランチ戦略 2026年版',
    url: 'https://qiita.com/',
    author: 'git_master',
    authorUrl: 'https://qiita.com/',
    likes: 654,
    source: 'qiita',
    tags: ['Git', 'GitHub', 'チーム開発'],
    publishedAt: daysAgo(3),
    excerpt:
      'trunk-based development を中心に、チーム規模やリリース頻度に応じたブランチ戦略の選び方を整理しました。',
  },
  {
    id: 'zenn:sample-3',
    title: 'Next.js App Routerのキャッシュを完全に理解する',
    url: 'https://zenn.dev/',
    author: 'next_fan',
    authorUrl: 'https://zenn.dev/',
    likes: 612,
    source: 'zenn',
    tags: ['Next.js', 'React', 'フロントエンド'],
    publishedAt: daysAgo(4),
    excerpt: '',
  },
  {
    id: 'qiita:sample-4',
    title: 'Dockerイメージを10分の1に軽量化したテクニック集',
    url: 'https://qiita.com/',
    author: 'infra_taro',
    authorUrl: 'https://qiita.com/',
    likes: 540,
    source: 'qiita',
    tags: ['Docker', 'インフラ', 'DevOps'],
    publishedAt: daysAgo(5),
    excerpt:
      'マルチステージビルド、distrolessイメージ、依存の整理など、本番イメージのサイズを劇的に減らす方法をまとめました。',
  },
  {
    id: 'zenn:sample-4',
    title: 'Go言語で学ぶ並行処理のパターン',
    url: 'https://zenn.dev/',
    author: 'gopher',
    authorUrl: 'https://zenn.dev/',
    likes: 488,
    source: 'zenn',
    tags: ['Go', '並行処理'],
    publishedAt: daysAgo(6),
    excerpt: '',
  },
  {
    id: 'qiita:sample-5',
    title: '初心者がやりがちなSQLアンチパターンと改善案',
    url: 'https://qiita.com/',
    author: 'db_hanako',
    authorUrl: 'https://qiita.com/',
    likes: 432,
    source: 'qiita',
    tags: ['SQL', 'データベース', 'パフォーマンス'],
    publishedAt: daysAgo(8),
    excerpt:
      'N+1クエリ、インデックスの貼り忘れ、暗黙の型変換など、よくあるSQLの落とし穴とその直し方を実例で解説します。',
  },
  {
    id: 'zenn:sample-5',
    title: 'Cloudflare Workersで作るサーバーレスAPI',
    url: 'https://zenn.dev/',
    author: 'edge_dev',
    authorUrl: 'https://zenn.dev/',
    likes: 401,
    source: 'zenn',
    tags: ['Cloudflare', 'サーバーレス'],
    publishedAt: daysAgo(10),
    excerpt: '',
  },
  {
    id: 'qiita:sample-6',
    title: 'VSCodeの拡張機能を自作して開発効率を爆上げした話',
    url: 'https://qiita.com/',
    author: 'tooling_dev',
    authorUrl: 'https://qiita.com/',
    likes: 376,
    source: 'qiita',
    tags: ['VSCode', 'TypeScript', '生産性'],
    publishedAt: daysAgo(12),
    excerpt:
      '日々の繰り返し作業を減らすために作ったVSCode拡張の開発手順と、公開までの流れを紹介します。',
  },
  {
    id: 'zenn:sample-6',
    title: 'Kubernetesの監視をゼロから設計する',
    url: 'https://zenn.dev/',
    author: 'sre_jiro',
    authorUrl: 'https://zenn.dev/',
    likes: 322,
    source: 'zenn',
    tags: ['Kubernetes', 'SRE', '監視'],
    publishedAt: daysAgo(15),
    excerpt: '',
  },
  {
    id: 'qiita:sample-7',
    title: 'リーダブルなReactコンポーネント設計の原則',
    url: 'https://qiita.com/',
    author: 'react_dev',
    authorUrl: 'https://qiita.com/',
    likes: 298,
    source: 'qiita',
    tags: ['React', 'フロントエンド', '設計'],
    publishedAt: daysAgo(18),
    excerpt:
      '責務の分離、状態の置き場所、Propsの設計など、保守しやすいコンポーネントを書くための指針をまとめました。',
  },
  {
    id: 'zenn:sample-7',
    title: 'PostgreSQLのインデックスを正しく使うための基礎',
    url: 'https://zenn.dev/',
    author: 'pg_dev',
    authorUrl: 'https://zenn.dev/',
    likes: 256,
    source: 'zenn',
    tags: ['PostgreSQL', 'データベース'],
    publishedAt: daysAgo(22),
    excerpt: '',
  },
];
